### ISSUE TITLE
Error: Cannot find module 'utf8mb4-converter/lib/cli'

### ISSUE THREAD

**Issue by xlttj** [building5/utf8mb4-converter#1]
```
$ npm install -g https://github.com/building5/utf8mb4-converter.git

$ utf8mb4-converter
module.js:338
    throw err;
    ^

Error: Cannot find module 'utf8mb4-converter/lib/cli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/utf8mb4-converter/bin/utf8mb4-converter.js:3:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

**Comment by leedm777** [comment]
@axel-tietje What versions of Node.js and NPM are you using? Worked for me with Node v6.9.1 and NPM v3.10.8.

**Comment by xlttj** [comment]
My versions are older. I tried to use it on an Ubuntu 14.04 LTS. I'll upgrade node/npm and report back. Thanks!

**Comment by wavvves** [comment]
Same problem here on node 7.8.0..

Also, does this alter MyISAM tables to InnoDb?

**Comment by leedm777** [comment]
I'm seeing that too on Node v7. I'm guessing bitrot claims another victim.

I can't dig into this right now, so PRs welcome if anyone wants to fix this.

> Also, does this alter MyISAM tables to InnoDb?

No.

**Comment by serena-lg** [comment]
Same problem on node 6.9.1 and npm 4.2.0.

**Comment by stewartjohnson** [comment]
I get this error with node v8.50 and npm 5.3.0.
